siteTitle="Geographer"
baseColor = "#884499"
linkPrefix = "/"
docPages = [
  "/documentation/",
  "/documentation/getting-started/",
  "/documentation/how-to-run/",
  "/documentation/some-react-code/",
  "/documentation/the-next-step/",
  "/documentation/test/",
  "/documentation/conclusion/",
]
