siteTitle = "Geographer"
baseColor = "#884499"
linkPrefix = "/"
docPages = [
  "/documentation/php/",
  "/documentation/php/getting-started/",
  "/documentation/php/basic-usage/",
  "/documentation/php/collections-common-methods/",
  "/documentation/php/earth/",
  "/documentation/php/country/",
  "/documentation/php/state/",
  "/documentation/php/city/",
  "/documentation/php/integrations/",
  "/documentation/js/",
  "/documentation/js/getting-started/",
  "/documentation/js/basic-usage/",
]
